/**
 * TicketService API
 * Ticketordering by date
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Seat } from './seat';
import { Show } from './show';


export interface Booking { 
    bookingID?: number;
    customerID?: string;
    seats?: Array<Seat>;
    show?: Show;
    date?: Date;
    totalPrice?: number;
}